import Image1 from "@/public/cats/image-1.webp";
import Image2 from "@/public/cats/image-2.webp";
import Image3 from "@/public/cats/image-3.webp";
import Image4 from "@/public/cats/image-4.webp";
import Image5 from "@/public/cats/image-5.webp";
import Image6 from "@/public/cats/image-6.webp";
import { IMenu } from "@/types/menu/menu-types";

export const departmentsImageData = [
  { id: 1, image: Image1 },
  { id: 2, image: Image2 },
  { id: 3, image: Image3 },
  { id: 4, image: Image4 },
  { id: 5, image: Image5 },
  { id: 6, image: Image6 },
  { id: 1, image: Image1 },
  { id: 10, image: Image1 },
  { id: 11, image: Image2 },
  { id: 12, image: Image3 },
  { id: 13, image: Image4 },
  { id: 14, image: Image5 },
  { id: 15, image: Image6 },
];

export const exampleMenu: IMenu = {
  menu_id: 10,
  menu_name: "Example Menu",
  menu_description: "Example Menu Description",
  menu_created_at: new Date(),
  menu_updated_at: new Date(),
  categories: [
    {
      category_id: 1,
      category_name: "Appetizers",
      category_description: "Delicious starters",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 1,
          title: `Appetizer ${i + 1}`,
          price: Math.floor(Math.random() * 50) + 30,
          discount: 10,
          available: Math.floor(Math.random() * 20) + 10,
          featured: Math.random() > 0.5,
          level: 1,
          thumbnail: {
            id: i + 1,
            name: `Appetizer ${i + 1}`,
            url: Image1.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 10,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 2,
      category_name: "Main Courses",
      category_description: "Hearty entrees",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 7,
          title: `Main Course ${i + 1}`,
          price: Math.floor(Math.random() * 100) + 50,
          discount: 15,
          available: Math.floor(Math.random() * 20) + 10,
          featured: Math.random() > 0.5,
          level: 2,
          thumbnail: {
            id: i + 7,
            name: `Main Course ${i + 1}`,
            url: Image2.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 15,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 3,
      category_name: "Desserts",
      category_description: "Sweet treats",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 13,
          title: `Dessert ${i + 1}`,
          price: Math.floor(Math.random() * 30) + 20,
          discount: 5,
          available: Math.floor(Math.random() * 20) + 10,
          featured: Math.random() > 0.5,
          level: 1,
          thumbnail: {
            id: i + 13,
            name: `Dessert ${i + 1}`,
            url: Image3.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 5,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 4,
      category_name: "Beverages",
      category_description: "Refreshing drinks",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 19,
          title: `Beverage ${i + 1}`,
          price: Math.floor(Math.random() * 20) + 10,
          discount: 0,
          available: Math.floor(Math.random() * 50) + 20,
          featured: Math.random() > 0.5,
          level: 1,
          thumbnail: {
            id: i + 19,
            name: `Beverage ${i + 1}`,
            url: Image4.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 0,
          discount_type: "percentage",
          discount_value: 0,
          discount_start_date: null,
          discount_end_date: null,
        })),
    },
    {
      category_id: 5,
      category_name: "Salads",
      category_description: "Fresh and healthy",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 25,
          title: `Salad ${i + 1}`,
          price: Math.floor(Math.random() * 40) + 30,
          discount: 8,
          available: Math.floor(Math.random() * 20) + 10,
          featured: Math.random() > 0.5,
          level: 1,
          thumbnail: {
            id: i + 25,
            name: `Salad ${i + 1}`,
            url: Image5.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 8,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 6,
      category_name: "Soups",
      category_description: "Warm and comforting",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 31,
          title: `Soup ${i + 1}`,
          price: Math.floor(Math.random() * 25) + 20,
          discount: 12,
          available: Math.floor(Math.random() * 20) + 10,
          featured: Math.random() > 0.5,
          level: 1,
          thumbnail: {
            id: i + 31,
            name: `Soup ${i + 1}`,
            url: Image6.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 12,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 7,
      category_name: "Pasta",
      category_description: "Italian favorites",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 37,
          title: `Pasta ${i + 1}`,
          price: Math.floor(Math.random() * 45) + 35,
          discount: 10,
          available: Math.floor(Math.random() * 20) + 10,
          featured: Math.random() > 0.5,
          level: 2,
          thumbnail: {
            id: i + 37,
            name: `Pasta ${i + 1}`,
            url: Image1.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 10,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 8,
      category_name: "Seafood",
      category_description: "Fresh from the ocean",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 43,
          title: `Seafood ${i + 1}`,
          price: Math.floor(Math.random() * 150) + 100,
          discount: 20,
          available: Math.floor(Math.random() * 15) + 5,
          featured: Math.random() > 0.5,
          level: 3,
          thumbnail: {
            id: i + 43,
            name: `Seafood ${i + 1}`,
            url: Image2.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 20,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 9,
      category_name: "Sides",
      category_description: "Perfect accompaniments",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 49,
          title: `Side ${i + 1}`,
          price: Math.floor(Math.random() * 20) + 15,
          discount: 5,
          available: Math.floor(Math.random() * 30) + 20,
          featured: Math.random() > 0.5,
          level: 1,
          thumbnail: {
            id: i + 49,
            name: `Side ${i + 1}`,
            url: Image3.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 5,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
    {
      category_id: 10,
      category_name: "Specials",
      category_description: "Chef's special selections",
      category_status: 1,
      products: Array(6)
        .fill(null)
        .map((_, i) => ({
          id: i + 55,
          title: `Special ${i + 1}`,
          price: Math.floor(Math.random() * 200) + 150,
          discount: 25,
          available: Math.floor(Math.random() * 10) + 5,
          featured: true,
          level: 3,
          thumbnail: {
            id: i + 55,
            name: `Special ${i + 1}`,
            url: Image4.src,
          },
          album: [
            Image1.src,
            Image2.src,
            Image3.src,
            Image4.src,
            Image5.src,
            Image6.src,
          ],
          has_discount: 1,
          discount_type: "percentage",
          discount_value: 25,
          discount_start_date: new Date(),
          discount_end_date: new Date(),
        })),
    },
  ],
};
